server:
  port: 8881

spring:
  batch:
    job:
      names: ${job.name:NONE}
      # Spring Batch 특정 Job만 실행하기
  config:
    activate:
      on-profile:
        - local
  datasource:
    url: jdbc:mariadb://localhost:3306/kotilnblog?serverTimezone=Asia/Seoul&useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf8
    username: test
    password: Test@12345678

  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    open-in-view: false
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        globally_quoted_identifiers: true