


logging:
  level:
    root: info
    com.example.batch: debug

spring:
  application:
    name: core-batch
  profiles:
    active:
      - local
  output:
    ansi:
      enabled: always

decorator:
  datasource:
    p6spy:
      enable-logging: true