server:
  port: 9000
  servlet:
    context-path: /
    encoding:
      charset: utf-8
      enabled: true


spring:
  profiles:
    active: local
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  redis:
    host: localhost
    port: 6379
    database: 0
  output:
    ansi:
      enabled: always
  datasource:
    url: jdbc:mariadb://localhost:3306/kotilnblog?serverTimezone=Asia/Seoul&useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf8
    username: test
    password: Test@12345678
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    open-in-view: false
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        globally_quoted_identifiers: true


decorator:
  datasource:
    p6spy:
      enable-logging: true

