
server:
  port: 9000


spring:
  thymeleaf:
    cache: false
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  config:
    activate:
      on-profile: local

  redis:
    host: localhost
    port: 6379
    database: 0
  output:
    ansi:
      enabled: always
  datasource:
    url: jdbc:mariadb://localhost:3306/kotilnblog?serverTimezone=Asia/Seoul&useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf8
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    open-in-view: false
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        globally_quoted_identifiers: true
    show-sql: false

decorator:
  datasource:
    p6spy:
      enable-logging: true


jwt:
  access:
    secretKey: myAccessSecretKey
    expireSecond: 30
  refresh:
    secretKey: myRefreshSecretKey
    expireDay: 7
